# Generated by Django 2.2 on 2019-04-28 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20190427_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('Platform', models.CharField(max_length=10)),
                ('host', models.ManyToManyField(to='management.Hosts')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Users')),
            ],
        ),
    ]
