# Generated by Django 2.2 on 2019-05-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20190502_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hosts',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='applications',
            name='platform',
            field=models.CharField(choices=[('W2013', 'Windows Server 2013'), ('W2016', 'Windows Server 2016'), ('U1604', 'Ubuntu Server 16.04'), ('U1804', 'Ubuntu Server 18.04'), ('RH73', 'Red Hat 7.3')], default='W2016', max_length=5),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1),
        ),
    ]
