# Generated by Django 2.2 on 2019-05-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20190502_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='platform',
            field=models.CharField(choices=[('W2016', 'Windows Server 2016'), ('W2013', 'Windows Server 2013'), ('U1804', 'Ubuntu Server 18.04'), ('RH73', 'Red Hat 7.3'), ('U1604', 'Ubuntu Server 16.04')], default='W2016', max_length=5),
        ),
    ]
